src/objects/TFL_Service__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>TFL API Credentials</description>
    <fields>
        <fullName>Applciation_Keys__c</fullName>
        <label>Applciation Keys</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application_ID__c</fullName>
        <description>Application ID</description>
        <label>Application ID</label>
        <length>8</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Detail__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Include details of the disruptions that are causing the line status including the affected stops and routes</inlineHelpText>
        <label>Detail</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Endpoint_URL__c</fullName>
        <label>Endpoint URL</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mode__c</fullName>
        <inlineHelpText>A comma-separated list of modes to filter by. e.g. tube,dlr</inlineHelpText>
        <label>Mode</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>TFL Service</label>
</CustomObject>

src/classes/LondonTransportStatusControllerTest.cls
@isTest
private class LondonTransportStatusControllerTest {
    
    @isTest static void testGetCalloutSuccess() {
        
        TFL_Service__c api = new TFL_Service__c();
        api.Name = 'TFL Service Test';
        api.Endpoint_URL__c = 'https://api.tfl.gov.uk';
        api.Application_ID__c = 'fa4bc08c';
        api.Applciation_Keys__c = '42ca0ae864ca9866714305768bb67aed ';
        api.Mode__c = 'tube,dlr,overground';
        api.detail__c = false;
        insert api;
        
        Test.StartTest();
        	// Set mock callout class 
        	Test.setMock(HttpCalloutMock.class, new LondonTransportStatusMock());
        	PageReference pageRef = Page.LondonTransportStatus;
    		Test.setCurrentPage(pageRef);
            
            LondonTransportStatusController controller = new LondonTransportStatusController();
       		controller.getTubeStatus();
        	
        Test.stopTest();
        
        system.assertNotEquals(0, controller.statusWrapper.size());
                 
    }
}